// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBagQOdr-RnLqEdXXsVdHq_VrZGMbFZuWE',
    appId: '1:185948948533:web:75becd5b42b4768ba8097c',
    messagingSenderId: '185948948533',
    projectId: 'tunisiashop-b1332',
    authDomain: 'tunisiashop-b1332.firebaseapp.com',
    storageBucket: 'tunisiashop-b1332.firebasestorage.app',
    measurementId: 'G-SKTEJY8X2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzicxC2eQkGFIMdl_-RE8SiGjNA8BeGog',
    appId: '1:185948948533:android:dcbea40255c64a8ba8097c',
    messagingSenderId: '185948948533',
    projectId: 'tunisiashop-b1332',
    storageBucket: 'tunisiashop-b1332.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiOFDe8FVQP1EABKnfLQDxbkxA7fylcaA',
    appId: '1:185948948533:ios:eb286aafb93a4959a8097c',
    messagingSenderId: '185948948533',
    projectId: 'tunisiashop-b1332',
    storageBucket: 'tunisiashop-b1332.firebasestorage.app',
    iosBundleId: 'com.example.tStore',
  );
}
